name          'opentable-nssm'
version       '0.1.0'
source        'git://github.com/opentable/puppet-nssm'
author        'opentable'
summary       'Module to install the nssm (http://nssm.cc/)'
description   'Installs nssm (the Non-Sucking Service Manager)'
project_page  'https://github.com/opentable/puppet-nssm'
license       'MIT'
dependency    'puppetlabs/stdlib'
dependency    'opentable/download_file'
